<?php

add_action ('init', 'layotter_register_acf_field');
function layotter_register_acf_field()
{
    $enabled_post_types = Layotter_Settings::get_enabled_post_types();
    $acf_location = array();

    foreach ($enabled_post_types as $post_type) {
        $acf_location[] = array(
            array(
                'param'    => 'post_type',
                'operator' => '==',
                'value'    => $post_type,
            )
        );
    }


    if (Layotter_Settings::is_debug_mode_enabled()) {
        $instructions = sprintf(
            __('Debug mode enabled: Inspect and manually edit the JSON structure generated by Layotter. Use with caution. A faulty structure will break your page layout and content. Go to the <a href="%s">Layotter\'s settings page</a> to disable debug mode.', 'layotter'),
            admin_url('options-general.php?page=layotter-settings')
        );
    } else {
        $instructions = '<style type="text/css">#acf-group_layotter_post_content { display: none !important; }</style>';
    }

    register_field_group(
        array(
            'key'                   => 'group_layotter_post_content',
            'title'                 => 'Layotter debugging',
            'fields'                => array(
                array(
                    'key'               => 'field_layotter_post_content',
                    'label'             => 'Internal JSON structure',
                    'name'              => 'layotter_post_content',
                    'type'              => 'textarea',
                    'instructions'      => $instructions,
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                    'readonly'          => 0,
                    'disabled'          => 0,
                )
            ),
            'location'              => $acf_location,
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
        )
    );
}