<?php


/**
 * Replace TinyMCE with Layotter on Layotter-enabled screens
 */
add_action('admin_head', 'layotter_admin_head');
function layotter_admin_head() {
    if (!Layotter::is_enabled()) {
        return;
    }

    $post_type = get_post_type();

    // remove TinyMCE
    remove_post_type_support($post_type, 'editor');

    // insert layotter
    add_meta_box(
        'layotter_wrapper', // ID
        'Layotter', // title
        'layotter_output_interface', // callback
        $post_type, // post type for which to enable
        'normal', // position
        'high' // priority
    );
}


/**
 * Output backend HTML for Layotter
 *
 * @param $post object Post object as provided by Wordpress
 */
function layotter_output_interface($post) {
    // prepare JSON data for representation in textarea
    $content = get_post_field('post_content', $post->ID);
    $clean_content_for_textarea = htmlspecialchars($content);

    // output two hidden textareas:
    // #content will be treated like a regular editor by Wordpress, it'll contain only dummy data and will be filled
    // with a search dump after the post is saved
    // #layotter-json is where Layotter keeps the internal JSON data, the field's content will be saved to a custom
    // field after the post is saved

    $hidden_style = 'width: 1px; height: 1px; position: fixed; top: -999px; left: -999px;';
    echo '<textarea id="content" name="content" style="' . $hidden_style . '">' . $clean_content_for_textarea . '</textarea>';

    if (Layotter_Settings::is_debug_mode_enabled()) {
        echo '<p>';
        printf(__('Debug mode enabled: Inspect and manually edit the JSON structure generated by Layotter. Use with caution. A faulty structure will break your page layout and content. Go to <a href="%s">Layotter\'s settings page</a> to disable debug mode.', 'layotter'), admin_url('options-general.php?page=layotter-settings'));
        echo '</p>';
        echo '<textarea id="layotter-json" name="layotter_json" style="width: 100%; height: 200px;margin-bottom: 30px;"></textarea>';
    } else {
        echo '<textarea id="layotter-json" name="layotter_json" style="' . $hidden_style . '"></textarea>';
    }
    
    require_once __DIR__ . '/../views/editor.php';
}
