<?php


/**
 * Replace TinyMCE with Layotter on Layotter-enabled screens
 */
add_action('admin_head', 'layotter_admin_head');
function layotter_admin_head() {
    if (!Layotter::is_enabled()) {
        return;
    }

    $post_type = get_post_type();

    // remove TinyMCE
    remove_post_type_support($post_type, 'editor');

    // insert layotter
    add_meta_box(
        'layotter_wrapper', // ID
        'Layotter', // title
        'layotter_output_interface', // callback
        $post_type, // post type for which to enable
        'normal', // position
        'high' // priority
    );
}


/**
 * Output backend HTML for Layotter
 *
 * @param $post object Post object as provided by Wordpress
 */
function layotter_output_interface($post) {
    $hidden_style = 'width: 1px; height: 1px; position: fixed; top: -999px; left: -999px;';
    $visible_style = 'width: 100%; height: 200px;margin-bottom: 30px;';
    echo '<textarea id="content" name="content" style="' . $hidden_style . '"></textarea>';

    if (Layotter_Settings::is_debug_mode_enabled()) {
        echo '<p>';
        printf(__('Debug mode enabled: Inspect and manually edit the JSON structure generated by Layotter. Use with caution. A faulty structure will break your page layout and content. Go to <a href="%s">Layotter\'s settings page</a> to disable debug mode.', 'layotter'), admin_url('admin.php?page=layotter-settings'));
        echo '</p>';
        echo '<textarea id="layotter-json" name="layotter_json" style="' . $visible_style . '"></textarea>';
    } else {
        echo '<textarea id="layotter-json" name="layotter_json" style="' . $hidden_style . '"></textarea>';
    }
    
    require_once __DIR__ . '/../views/editor.php';
}


/**
 * Disables Wordpress 5 block editor for Layotter-enabled posts.
 *
 * @param bool $enabled Previous setting for the post type
 * @param string $post_type The post type in question
 * @return bool
 */
add_filter('use_block_editor_for_post_type', 'layotter_disable_gutenberg', 10, 2);
function layotter_disable_gutenberg($enabled, $post_type) {
    $layotter_post_types = Layotter_Settings::get_enabled_post_types();

    if (in_array($post_type, $layotter_post_types)) {
        return false;
    }

    return $enabled;
}
