<?php


/**
 * Abstract class for editable components (options and elements)
 */
abstract class Layotter_Editable {

    protected
        $clean_values = array(),
        $formatted_values = array(),
        $form;


    /**
     * Apply $this->clean_values and $this->formatted values, create $this->form
     *
     * @param array $fields Existing fields as provided by an ACF field group
     * @param array $values Array with user-provided values, or empty array if dealing with a new element
     */
    final protected function apply_values($fields, $values) {
        if (!is_array($fields)) {
            $fields = array();
        }

        if (!is_array($values)) {
            $values = array();
        }

        // parse provided values for use in different contexts
        $this->clean_values = $this->clean_values($fields, $values);
        $this->formatted_values = $this->format_values($fields, $this->clean_values);

        // create edit form
        $values_for_form = Layotter_ACF::prepare_values_for_form($fields, $this->clean_values);
        $this->form = new Layotter_Form($fields, $values_for_form);
    }


    /**
     * Clean user-provided values
     *
     * This method normalizes an array of user-provided field values. The return value is an array where the keys are
     * human-readable field names (as provided by the user in an ACF field group), and the values are unfiltered data
     * of any type (as provided by an element edit form or an existing post's JSON data).
     *
     * @param array $existing_fields Existing fields as provided by an ACF field group
     * @param array $provided_values Array with user-provided values, or empty array if dealing with a new element
     * @return array Clean values for use in forms and JSON
     */
    final protected static function clean_values($existing_fields, $provided_values = array()) {
        $values = array();

        // loop through existing fields and see if there's a user provided value for each one
        foreach ($existing_fields as $field_data) {
            $field_name = $field_data['name'];
            $field_key = $field_data['key'];

            // skip ACF 'tab' and 'message' fields to prevent pollution of $values with empty keys and values
            if (empty($field_name)) {
                continue;
            }

            // assign a value to this field
            if (isset($provided_values[$field_name])) {
                // either user provided value identified by name ...
                // (when $provided_values came from an existing post's JSON data)
                $values[$field_name] = $provided_values[$field_name];
            } else if (isset($provided_values[$field_key])) {
                // ... or user provided value identified by ACF key ...
                // (when $provided_values came from an edit form generated by ACF)
                $values[$field_name] = $provided_values[$field_key];
            } else if (isset($field_data['default_value'])) {
                // ... or set to default value ...
                $values[$field_name] = $field_data['default_value'];
            } else {
                // ... or fallback to null, to make sure all fields are present in the array
                $values[$field_name] = null;
            }

            // quick fix for broken Repeater fields
            if ($field_data['type'] == 'repeater' && is_array($values[$field_name])) {
                $values[$field_name] = array_values($values[$field_name]);
            }

            // note:
            // in default ACF, field values are run through the acf/validate_value and acf/update_value filters
            // before saving them to the database
            // these filters can break fields in Layotter's context and are therefore not applied
        }

        return $values;
    }


    /**
     * Format user-provided values for output
     *
     * @param array $existing_fields Existing fields as provided by an ACF field group
     * @param array $clean_values Array with clean values (that were run through $this->clean_values() first)
     * @return array Formatted values for output
     */
    final protected static function format_values($existing_fields, $clean_values) {
        $values = array();

        // run all provided values through formatting filters
        foreach ($existing_fields as $field_data) {
            $field_name = $field_data['name'];

            // skip ACF 'tab' and 'message' fields to prevent pollution of $values with empty keys and values
            if (empty($field_name)) {
                continue;
            }

            // note:
            // in default ACF, field values are run through the acf/load_value filter before formatting
            // this filter can break fields in Layotter's context and is therefore not applied

            // format values using ACF's formatting filters
            $values[$field_name] = Layotter_ACF::format_value($clean_values[$field_name], $field_data);
        }

        return $values;
    }


    /**
     * Get clean values
     *
     * @return array Clean values
     */
    final public function get_clean_values() {
        return $this->clean_values;
    }


    /**
     * Get formatted values
     *
     * @return array Formatted values
     */
    final public function get_formatted_values() {
        return $this->formatted_values;
    }


    /**
     * Output edit form for this component
     */
    final public function get_form_data() {
        return $this->form->get_data();
    }

}
